### ISSUE TITLE
Error running after fresh install

### ISSUE THREAD

**Issue by iamnewton** [filamentgroup/node-faux-pas#1]
Using: node v7.8.0; npm 4.2.0

```
#2219: $ fauxpas --url https://optionb.org
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'node_modules/fg-faux-pas/faux-pas.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-faux-pas/index.js:11:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
```

**Comment by zachleat** [comment]
Included with v1.0.1—thank you!
